Improove documentation
s-ol/themer pull request #49
Opened 2017-04-08 15:53 UTC by Kaligule

From what I learned today, this is the summary. Maybe someone should look over it, but it is better then nothing and definitelly would have helped me.

2017-04-09 02:37 UTC, Kaligule commented
This adresses #46 and #47.

2017-04-09 09:34 UTC, s-ol commented
looks pretty good overall.

2017-04-10 08:19 UTC, s-ol requested changes

2017-04-10 08:19 UTC, s-ol commented on README.md
> +- as many themes (which are directories) as you want. These hold the
"as you want" implies you create these, but usually they are generated for you, I would mention this to make it clear that `templates` and `current` are what you come in contact with and that the others are mostly for internal use

2017-04-10 17:12 UTC, Kaligule commented
I will change the pull request as soon as I have found out how to do it in github.

2017-04-10 17:14 UTC, Kaligule commented
It seems my additional commit (which adresses your issues) has gone into the pullrequest without me doing anything. I am not sure what to think about that but I can see that it worked in this case. Any more changes?

2017-04-10 18:29 UTC, s-ol commented
@Kaligule a PR is just a note to merge a branch on your repository with a branch on my repository (a *request* for me to *pull* your branch into my repo):

If you look at the top of this page, it says
>@Kaligule  wants to merge 6 commits into `s-ol:develop` from `Kaligule:develop`

As you can see the PR uses the branch labels, so when you update `Kaligule:develop` the PR changes as well. I'm not sure if Github supports this but theoretically the PR could be

> @Kaligule wants to merge 6 commits into `s-ol:develop` from e36527722bceee1a261f20f26d89ea6ec0828e9c

which would mean that when you change `develop` the PR stays the same. This is why usually you want to create a feature branch, like `update-documentation`, that is temporary so you can control it better on your end.

2017-04-10 18:31 UTC, s-ol commented
Theres one minor word change I'm gonna add myself, but yeah this is fine.

2017-04-10 18:33 UTC, Kaligule commented
So pull requests are about branches, not commits. I see my mistake. Thank you.

2017-04-10 18:40 UTC, s-ol commented
Closed in e8934aeba54c3a4c0c460e0180c409bf097e8ae7 (squashed)

2017-04-10 18:40 UTC, closed without merging